language: node_js
sudo: false
node_js:
  - '10'

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"
    - ".material-cache"

env:
  matrix:
  - MODE=TESTS
  - MODE=VERSIONS
  - MODE=LINT

install:
  - npm install

script:
  - "./scripts/run-travis.sh"
